#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time   : 3/15/18 10:32 PM
# @Author : Saseny.Zhou
# @File   : ui_show.py


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_error(object):
    def setupUi(self, show_error):
        show_error.setObjectName("show_error")
        show_error.resize(541, 280)
        self.centralwidget = QtWidgets.QWidget(show_error)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.serial_number = QtWidgets.QLabel(self.centralwidget)
        self.serial_number.setMinimumSize(QtCore.QSize(120, 0))
        self.serial_number.setStyleSheet("background-color: rgb(185, 255, 215);")
        self.serial_number.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_number.setObjectName("serial_number")
        self.horizontalLayout.addWidget(self.serial_number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dti_info = QtWidgets.QLabel(self.centralwidget)
        self.dti_info.setStyleSheet("background-color: rgb(188, 255, 192);")
        self.dti_info.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.dti_info.setObjectName("dti_info")
        self.horizontalLayout_2.addWidget(self.dti_info)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.path_road = QtWidgets.QLabel(self.centralwidget)
        self.path_road.setStyleSheet("background-color: rgb(196, 255, 197);")
        self.path_road.setObjectName("path_road")
        self.horizontalLayout_3.addWidget(self.path_road)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.error_code = QtWidgets.QLabel(self.centralwidget)
        self.error_code.setStyleSheet("color: rgb(9, 0, 255);\n"
                                      "background-color: rgb(255, 251, 235);")
        self.error_code.setObjectName("error_code")
        self.horizontalLayout_4.addWidget(self.error_code)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.listView = QtWidgets.QListWidget(self.groupBox)
        self.listView.setMinimumSize(QtCore.QSize(400, 0))
        self.listView.setStyleSheet("background-color: rgb(255, 245, 249);")
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 1, 3, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.count = QtWidgets.QLineEdit(self.groupBox)
        self.count.setStyleSheet("background-color: rgb(241, 255, 227);")
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setReadOnly(True)
        self.count.setObjectName("count")
        self.gridLayout.addWidget(self.count, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        show_error.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(show_error)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 22))
        self.menubar.setObjectName("menubar")
        show_error.setMenuBar(self.menubar)

        self.retranslateUi(show_error)
        QtCore.QMetaObject.connectSlotsByName(show_error)

    def retranslateUi(self, show_error):
        _translate = QtCore.QCoreApplication.translate
        show_error.setWindowTitle(_translate("show_error", "信息显示"))
        self.label.setText(_translate("show_error", "机器序列号:"))
        self.serial_number.setText(_translate("show_error", ""))
        self.label_3.setText(_translate("show_error", "DTI 信息:"))
        self.dti_info.setText(_translate("show_error", ""))
        self.label_2.setText(_translate("show_error", "Log 路径:"))
        self.path_road.setText(_translate("show_error", ""))
        self.label_5.setText(_translate("show_error", "ErrorCode:"))
        self.error_code.setText(_translate("show_error", ""))
        self.label_7.setText(_translate("show_error", "未匹配Error:"))
        self.label_8.setText(_translate("show_error", "未匹配数:"))
        self.count.setText(_translate("show_error", "3"))
