#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time   : 3/15/18 10:32 PM
# @Author : Saseny.Zhou
# @File   : ui_show.py

from PyQt5 import QtCore, QtGui, QtWidgets
from Path.path import *


class Ui_show(object):
    def setupUi(self, show):
        show.setObjectName("show")
        show.resize(667, 396)
        self.centralwidget = QtWidgets.QWidget(show)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(120, 40))
        self.label.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.serial_number = QtWidgets.QLineEdit(self.centralwidget)
        self.serial_number.setMinimumSize(QtCore.QSize(0, 40))
        self.serial_number.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.serial_number.setFont(font)
        self.serial_number.setStyleSheet("font: 25 22pt \"STFangsong\";\n"
                                         "background-color: rgb(236, 255, 214);\n"
                                         "color: rgb(252, 0, 12);")
        self.serial_number.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_number.setReadOnly(True)
        self.serial_number.setObjectName("serial_number")
        self.gridLayout_2.addWidget(self.serial_number, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 40))
        self.label_5.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setLineWidth(2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.runTime = QtWidgets.QLineEdit(self.centralwidget)
        self.runTime.setMinimumSize(QtCore.QSize(0, 40))
        self.runTime.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.runTime.setFont(font)
        self.runTime.setStyleSheet("font: 25 18pt \"STFangsong\";\n"
                                   "background-color: rgb(236, 255, 214);\n"
                                   "color: rgb(15, 0, 255);")
        self.runTime.setAlignment(QtCore.Qt.AlignCenter)
        self.runTime.setReadOnly(True)
        self.runTime.setObjectName("runTime")
        self.gridLayout_2.addWidget(self.runTime, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 40))
        self.label_2.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.dti_info = QtWidgets.QLineEdit(self.centralwidget)
        self.dti_info.setMinimumSize(QtCore.QSize(0, 40))
        self.dti_info.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dti_info.setFont(font)
        self.dti_info.setStyleSheet("font: 25 13pt \"STFangsong\";\n"
                                    "background-color: rgb(236, 255, 214);\n"
                                    "color: rgb(0, 0, 3);")
        self.dti_info.setReadOnly(True)
        self.dti_info.setObjectName("dti_info")
        self.gridLayout_2.addWidget(self.dti_info, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(120, 40))
        self.label_3.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setLineWidth(2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.path_road = QtWidgets.QLineEdit(self.centralwidget)
        self.path_road.setMinimumSize(QtCore.QSize(0, 40))
        self.path_road.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.path_road.setFont(font)
        self.path_road.setStyleSheet("font: 25 18pt \"STFangsong\";\n"
                                     "background-color: rgb(236, 255, 214);\n"
                                     "color: rgb(27, 0, 255);")
        self.path_road.setReadOnly(True)
        self.path_road.setObjectName("path_road")
        self.gridLayout_2.addWidget(self.path_road, 2, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 40))
        self.label_4.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setLineWidth(2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.error_code = QtWidgets.QLineEdit(self.centralwidget)
        self.error_code.setMinimumSize(QtCore.QSize(0, 40))
        self.error_code.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.error_code.setFont(font)
        self.error_code.setStyleSheet("font: 25 20pt \"STFangsong\";\n"
                                      "background-color: rgb(236, 255, 214);\n"
                                      "color: rgb(252, 20, 27);")
        self.error_code.setReadOnly(True)
        self.error_code.setObjectName("error_code")
        self.gridLayout_2.addWidget(self.error_code, 3, 1, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(120, 40))
        self.label_6.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(196, 255, 178);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setLineWidth(2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.listView = QtWidgets.QListWidget(self.groupBox)
        self.listView.setStyleSheet("background-color: rgb(255, 243, 232);")
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 1, 3, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(120, 40))
        self.label_7.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(196, 255, 178);\n"
                                   "")
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setLineWidth(2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.count = QtWidgets.QLineEdit(self.groupBox)
        self.count.setMinimumSize(QtCore.QSize(120, 40))
        self.count.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.count.setFont(font)
        self.count.setStyleSheet("background-color: rgb(215, 255, 235);")
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setReadOnly(True)
        self.count.setObjectName("count")
        self.gridLayout.addWidget(self.count, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 4, 0, 1, 4)
        show.setCentralWidget(self.centralwidget)

        self.retranslateUi(show)
        QtCore.QMetaObject.connectSlotsByName(show)

    def retranslateUi(self, show):
        _translate = QtCore.QCoreApplication.translate
        show.setWindowTitle(_translate("show", "机器信息"))
        self.label.setText(_translate("show", "机器序列号:"))
        self.serial_number.setText(_translate("show", ""))
        self.label_5.setText(_translate("show", "Run-in 时间"))
        self.runTime.setText(_translate("show", ""))
        self.label_2.setText(_translate("show", "DTI 信息"))
        self.dti_info.setText(
            _translate("show", ""))
        self.label_3.setText(_translate("show", "Log 路径"))
        self.path_road.setText(_translate("show", ""))
        self.label_4.setText(_translate("show", "Error Code"))
        self.error_code.setText(_translate("show",
                                           ""))
        self.label_6.setText(_translate("show", "未匹配 Error"))
        self.label_7.setText(_translate("show", "未匹配个数"))
        self.count.setText(_translate("show", ""))
