#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time   : 3/14/18 10:43 PM
# @Author : Saseny.Zhou
# @File   : ui_main.py


from PyQt5 import QtCore, QtGui, QtWidgets
from Path.path import *


class Ui_BurninTools(object):
    def setupUi(self, BurninTools):
        BurninTools.setObjectName("BurninTools")
        BurninTools.resize(320, 220)
        BurninTools.setStyleSheet("font: 25 14pt \"STFangsong\";")
        self.centralWidget = QtWidgets.QWidget(BurninTools)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 160))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setStyleSheet("background-color: rgb(255, 238, 232);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 145))
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: 25 36pt \"STFangsong\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("STFangsong")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "font: 25 18pt \"STFangsong\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        BurninTools.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(BurninTools)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 338, 22))
        self.menuBar.setObjectName("menuBar")
        BurninTools.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(BurninTools)
        self.mainToolBar.setIconSize(QtCore.QSize(20, 20))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        BurninTools.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionload_units = QtWidgets.QAction(BurninTools)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(imagePath + "/load_units.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionload_units.setIcon(icon)
        self.actionload_units.setObjectName("actionload_units")
        self.actionload_error = QtWidgets.QAction(BurninTools)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(imagePath + "/load_error.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionload_error.setIcon(icon1)
        self.actionload_error.setObjectName("actionload_error")
        self.actionsearch = QtWidgets.QAction(BurninTools)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(imagePath + "/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsearch.setIcon(icon2)
        self.actionsearch.setObjectName("actionsearch")
        self.mainToolBar.addAction(self.actionload_units)
        self.mainToolBar.addAction(self.actionload_error)
        self.mainToolBar.addAction(self.actionsearch)

        self.retranslateUi(BurninTools)

        self.pushButton.clicked.connect(self.start)
        self.actionload_units.triggered.connect(self.loadUnits)
        self.actionload_error.triggered.connect(self.loadError)
        self.actionsearch.triggered.connect(self.searchInfo)

        QtCore.QMetaObject.connectSlotsByName(BurninTools)

    def retranslateUi(self, BurninTools):
        _translate = QtCore.QCoreApplication.translate
        BurninTools.setWindowTitle(_translate("BurninTools", "BurninTools"))
        self.label.setText(_translate("BurninTools", " 功能选择:"))
        self.pushButton.setText(_translate("BurninTools", "开始"))
        self.label_2.setText(_translate("BurninTools", "等待开始!"))
        self.actionload_units.setText(_translate("BurninTools", "机器信息加载"))
        self.actionload_units.setToolTip(_translate("BurninTools", "加载机器信息"))
        self.actionload_units.setShortcut(_translate("BurninTools", "Ctrl+U"))
        self.actionload_error.setText(_translate("BurninTools", "不良信息加载"))
        self.actionload_error.setToolTip(_translate("BurninTools", "加载不良信息"))
        self.actionload_error.setShortcut(_translate("BurninTools", "Ctrl+E"))
        self.actionsearch.setText(_translate("BurninTools", "搜索机器"))
        self.actionsearch.setToolTip(_translate("BurninTools", "搜索机器信息"))
        self.actionsearch.setShortcut(_translate("BurninTools", "Ctrl+F"))
