# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/saseny/Desktop/0902/monitor/monitortools.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_monitorTools(object):
    def setupUi(self, monitorTools):
        monitorTools.setObjectName("monitorTools")
        monitorTools.resize(1253, 829)
        self.centralWidget = QtWidgets.QWidget(monitorTools)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 951, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 921, 681))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 921, 681))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 911, 651))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(800, 662, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1010, 30, 211, 61))
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralWidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1000, 600, 241, 173))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 60, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(1030, 130, 181, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1030, 230, 181, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1030, 330, 181, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(1040, 460, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1132, 490, 71, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(1035, 515, 100, 16))
        self.label_2.setObjectName("label_2")
        monitorTools.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(monitorTools)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1253, 22))
        self.menuBar.setObjectName("menuBar")
        monitorTools.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(monitorTools)
        self.statusBar.setObjectName("statusBar")
        monitorTools.setStatusBar(self.statusBar)
        #self.tableWidget

        self.retranslateUi(monitorTools)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(self.clearLogsButton)
        self.pushButton.clicked.connect(self.startButton)
        self.pushButton_2.clicked.connect(self.clearButton)
        self.pushButton_3.clicked.connect(self.onceUpdate)
        self.pushButton_5.clicked.connect(self.addIp)
        # self.pushButton.clicked.connect(self.onceUpdate)
        # self.pushButton_2.clicked.connect(self.tableWidget_2.clear)
        QtCore.QMetaObject.connectSlotsByName(monitorTools)

    def retranslateUi(self, monitorTools):
        _translate = QtCore.QCoreApplication.translate
        monitorTools.setWindowTitle(_translate("monitorTools", "monitorTools"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("monitorTools", "线别"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("monitorTools", "站别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("monitorTools", "站ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("monitorTools", "IP地址"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("monitorTools", "磁盘状态"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("monitorTools", "BobCat"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("monitorTools", "Overlay"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("monitorTools", "刷新时间"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("monitorTools", "其他"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("monitorTools", "J79A"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("monitorTools", "线别"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("monitorTools", "站别"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("monitorTools", "站ID"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("monitorTools", "IP地址"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("monitorTools", "磁盘状态"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("monitorTools", "BobCat"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("monitorTools", "Overlay"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("monitorTools", "刷新时间"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("monitorTools", "其他"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("monitorTools", "J80A"))
        self.pushButton_4.setText(_translate("monitorTools", "清除记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("monitorTools", "LOGS"))
        self.label.setText(_translate("monitorTools", "Version"))
        self.pushButton.setText(_translate("monitorTools", "开始"))
        self.pushButton_2.setText(_translate("monitorTools", "清除"))
        self.pushButton_3.setText(_translate("monitorTools", "单次刷新"))
        self.pushButton_5.setText(_translate("monitorTools", "Add"))
        self.label_2.setText(_translate("monitorTools", "waiting"))
