# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/saseny/PycharmProjects/Monitor_Create/monitor/monitor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_monitor(object):
    def setupUi(self, monitor):
        monitor.setObjectName("monitor")
        monitor.resize(1111, 845)
        self.centralWidget = QtWidgets.QWidget(monitor)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1071, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 361, 351))
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 50, 301, 71))
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 150, 321, 173))
        self.calendarWidget.setObjectName("calendarWidget")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(430, 50, 611, 431))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(430, 520, 611, 241))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 380, 361, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 321, 21))
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(210, 60, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 171, 31))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(0, 100, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 161, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 140, 161, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 250, 161, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 310, 161, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(0, 230, 361, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 270, 151, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 300, 151, 51))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(430, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(430, 490, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(960, 0, 81, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 1041, 721))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(940, 0, 111, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 10, 81, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 10, 81, 32))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(810, 0, 113, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 40, 1041, 721))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(940, 0, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 10, 81, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 10, 81, 32))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(810, 0, 113, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 40, 1041, 721))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(10)
        self.tableWidget_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(940, 0, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 10, 81, 32))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(80, 10, 81, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_17.setGeometry(QtCore.QRect(810, 0, 113, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.tabWidget.addTab(self.tab_4, "")
        monitor.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(monitor)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1111, 22))
        self.menuBar.setObjectName("menuBar")
        monitor.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(monitor)
        self.statusBar.setObjectName("statusBar")
        monitor.setStatusBar(self.statusBar)

        self.retranslateUi(monitor)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(self.textEdit.clear)
        self.pushButton_5.clicked.connect(self.textEdit_2.clear)
        self.pushButton_6.clicked.connect(self.tableWidget.clearContents)
        self.pushButton_7.clicked.connect(self.tableWidget_2.clearContents)
        self.pushButton_8.clicked.connect(self.tableWidget_3.clearContents)
        self.lineEdit.selectionChanged.connect(self.lineEdit.show)
        self.pushButton_15.clicked.connect(self.tableWidget.update)
        self.pushButton_16.clicked.connect(self.tableWidget_2.update)
        self.pushButton_17.clicked.connect(self.tableWidget_3.update)
        QtCore.QMetaObject.connectSlotsByName(monitor)

    def retranslateUi(self, monitor):
        _translate = QtCore.QCoreApplication.translate
        monitor.setWindowTitle(_translate("monitor", "monitor"))
        self.groupBox.setTitle(_translate("monitor", "时间显示区域"))
        self.groupBox_2.setTitle(_translate("monitor", "功能使用区域"))
        self.lineEdit.setPlaceholderText(_translate("monitor", "可输入文件路径或单个地址或多个地址以空格分开"))
        self.pushButton.setText(_translate("monitor", "地址添加"))
        self.label_5.setText(_translate("monitor", "返回信息"))
        self.pushButton_2.setText(_translate("monitor", "开始刷新"))
        self.pushButton_3.setText(_translate("monitor", "单次刷新"))
        self.pushButton_4.setText(_translate("monitor", "清除记录 - 监控信息"))
        self.pushButton_5.setText(_translate("monitor", "清除记录 - 失败信息"))
        self.pushButton_18.setText(_translate("monitor", "导出IP信息变化"))
        self.label.setText(_translate("monitor", "监控记录信息"))
        self.label_2.setText(_translate("monitor", "远程失败信息"))
        self.groupBox_3.setTitle(_translate("monitor", "版本"))
        self.label_3.setText(_translate("monitor", "1.0.7"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("monitor", "Main Window"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("monitor", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("monitor", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("monitor", "线别"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("monitor", "站别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("monitor", "ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("monitor", "IP地址"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("monitor", "磁盘状态"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("monitor", "剩余空间"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("monitor", "BobCat"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("monitor", "Overlay"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("monitor", "刷新时间"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("monitor", "机种"))
        self.pushButton_6.setText(_translate("monitor", "清空表格"))
        self.pushButton_9.setText(_translate("monitor", "Disable"))
        self.pushButton_12.setText(_translate("monitor", "Enable"))
        self.pushButton_15.setText(_translate("monitor", "更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("monitor", "79 Product"))
        self.tableWidget_2.setSortingEnabled(True)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("monitor", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("monitor", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("monitor", "线别"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("monitor", "站别"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("monitor", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("monitor", "IP地址"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("monitor", "磁盘状态"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("monitor", "剩余空间"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("monitor", "BobCat"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("monitor", "Overlay"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("monitor", "刷新时间"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("monitor", "机种"))
        self.pushButton_7.setText(_translate("monitor", "清空表格"))
        self.pushButton_10.setText(_translate("monitor", "Disable"))
        self.pushButton_13.setText(_translate("monitor", "Enable"))
        self.pushButton_16.setText(_translate("monitor", "更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("monitor", "80 Product"))
        self.tableWidget_3.setSortingEnabled(True)
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("monitor", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("monitor", "2"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("monitor", "线别"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("monitor", "站别"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("monitor", "ID"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("monitor", "IP地址"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("monitor", "磁盘状态"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("monitor", "剩余空间"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("monitor", "BobCat"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("monitor", "Overlay"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("monitor", "刷新时间"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("monitor", "机种"))
        self.pushButton_8.setText(_translate("monitor", "清空表格"))
        self.pushButton_11.setText(_translate("monitor", "Disable"))
        self.pushButton_14.setText(_translate("monitor", "Enable"))
        self.pushButton_17.setText(_translate("monitor", "更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("monitor", "Others"))

