# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/saseny/PycharmProjects/MODULE/MyTools/mytools.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MyTools(object):
    def setupUi(self, MyTools):
        MyTools.setObjectName("MyTools")
        MyTools.resize(1231, 876)
        self.centralWidget = QtWidgets.QWidget(MyTools)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(19, 69, 1021, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1011, 741))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdNumber.setGeometry(QtCore.QRect(890, 10, 121, 41))
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 871, 691))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 700, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_2)
        self.timeEdit.setGeometry(QtCore.QRect(180, 10, 118, 24))
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(60, 10, 110, 24))
        self.dateEdit.setDate(QtCore.QDate(2017, 9, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 60, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(340, 10, 60, 21))
        self.label_2.setObjectName("label_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit_2.setGeometry(QtCore.QRect(370, 10, 110, 24))
        self.dateEdit_2.setDate(QtCore.QDate(2017, 9, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_2)
        self.timeEdit_2.setGeometry(QtCore.QRect(490, 10, 118, 24))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(890, 130, 121, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(890, 380, 113, 21))
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(890, 450, 113, 21))
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(890, 500, 113, 21))
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(890, 360, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(890, 430, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(890, 480, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(890, 110, 100, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(890, 660, 121, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 871, 731))
        self.tableWidget.setRowCount(50)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(890, 10, 113, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(890, 60, 113, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(890, 110, 113, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(1010, 10, 211, 61))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(490, 30, 501, 21))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 10, 191, 51))
        self.lcdNumber_2.setDigitCount(8)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1050, 520, 171, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(1050, 650, 171, 131))
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(1040, 500, 191, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(1050, 90, 171, 401))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1060, 790, 151, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(1060, 580, 151, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        MyTools.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MyTools)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1231, 22))
        self.menuBar.setObjectName("menuBar")
        MyTools.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MyTools)
        self.statusBar.setObjectName("statusBar")
        MyTools.setStatusBar(self.statusBar)
        
        self.label_4.showFullScreen()

        self.tableWidget.setColumnWidth(0, 203)
        self.tableWidget.setColumnWidth(1, 115)
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 100)
        self.tableWidget.setColumnWidth(4, 115)
        self.tableWidget.setColumnWidth(5, 100)
        self.tableWidget.setColumnWidth(6, 110)

        self.retranslateUi(MyTools)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(self.picupdate)
        self.pushButton.clicked.connect(self.textEdit.show)
        self.textEdit.windowTitleChanged['QString'].connect(self.lcdNumber.update)
        self.pushButton_4.clicked.connect(self.tableWidget.update)
        #self.pushButton_5.clicked.connect(self.writeCSVFile)
        self.pushButton_7.clicked.connect(self.picstore)
        
        self.pushButton_6.clicked.connect(self.tableWidget.clearContents)
        self.pushButton_2.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MyTools)

    def retranslateUi(self, MyTools):
        _translate = QtCore.QCoreApplication.translate
        MyTools.setWindowTitle(_translate("MyTools", "MyTools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MyTools", "窗口1"))
        self.pushButton_2.setText(_translate("MyTools", "Clear"))
        self.label.setText(_translate("MyTools", "From:"))
        self.label_2.setText(_translate("MyTools", "To:"))
        self.lineEdit_3.setText(_translate("MyTools", "17.239.64.36"))
        self.label_5.setText(_translate("MyTools", "PDCA IP"))
        self.label_6.setText(_translate("MyTools", "账户"))
        self.label_7.setText(_translate("MyTools", "密码"))
        self.label_8.setText(_translate("MyTools", "线别或者关键字"))
        self.pushButton_8.setText(_translate("MyTools", "Debug"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MyTools", "窗口2"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MyTools", "Station"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MyTools", "Total"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MyTools", "Pass"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MyTools", "Fail"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MyTools", "Yield"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MyTools", "Retest"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MyTools", "RetestRate"))
        self.pushButton_4.setText(_translate("MyTools", "加载数据"))
        self.pushButton_5.setText(_translate("MyTools", "生成文件"))
        self.pushButton_6.setText(_translate("MyTools", "清除表单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MyTools", "窗口3"))
        self.pushButton.setText(_translate("MyTools", "PushButton"))
        self.pushButton_3.setText(_translate("MyTools", "图片加载"))
        self.pushButton_7.setText(_translate("MyTools", "图片保存"))
        self.lineEdit_6.setText(_translate("MyTools", "Yield"))

