# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/saseny/Desktop/0916/GetPDCA/myapp.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_myApp(object):
    def setupUi(self, myApp):
        myApp.setObjectName("myApp")
        myApp.resize(1319, 912)
        self.centralWidget = QtWidgets.QWidget(myApp)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1131, 871))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 921, 821))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab_4)
        self.lcdNumber_2.setGeometry(QtCore.QRect(990, 10, 121, 41))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(940, 80, 181, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(940, 60, 111, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(940, 110, 91, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(1030, 110, 91, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(1020, 150, 91, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(950, 150, 91, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(940, 180, 181, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.line_3 = QtWidgets.QFrame(self.tab_4)
        self.line_3.setGeometry(QtCore.QRect(930, 660, 201, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(940, 680, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(980, 700, 141, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(950, 700, 21, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(1010, 740, 111, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(1010, 770, 111, 21))
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(940, 740, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(940, 770, 71, 16))
        self.label_7.setObjectName("label_7")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(930, 310, 201, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(940, 320, 171, 51))
        self.label_8.setScaledContents(False)
        self.label_8.setWordWrap(True)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(940, 380, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(940, 490, 71, 16))
        self.label_10.setObjectName("label_10")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit.setGeometry(QtCore.QRect(950, 410, 161, 24))
        self.dateEdit.setDate(QtCore.QDate(2017, 9, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit.setGeometry(QtCore.QRect(950, 440, 161, 24))
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit_2.setGeometry(QtCore.QRect(950, 520, 161, 24))
        self.dateEdit_2.setDate(QtCore.QDate(2017, 9, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit_2.setGeometry(QtCore.QRect(950, 550, 161, 24))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(940, 600, 181, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_12.setGeometry(QtCore.QRect(1042, 810, 81, 32))
        self.pushButton_12.setObjectName("pushButton_12")
        self.line_6 = QtWidgets.QFrame(self.tab_4)
        self.line_6.setGeometry(QtCore.QRect(930, 240, 201, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_15.setGeometry(QtCore.QRect(940, 250, 181, 61))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 971, 841))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(990, 0, 131, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 70, 131, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_3.setGeometry(QtCore.QRect(990, 140, 131, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_4.setGeometry(QtCore.QRect(1020, 540, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(990, 510, 131, 31))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 270, 1101, 561))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 1101, 211))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 30, 113, 32))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(980, 170, 113, 32))
        self.pushButton_16.setObjectName("pushButton_16")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 10, 651, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(660, 10, 51, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1150, 20, 161, 51))
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(1140, 570, 181, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_2.setGeometry(QtCore.QRect(1140, 610, 181, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1150, 640, 171, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(1150, 760, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(1150, 740, 71, 16))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(1140, 280, 181, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1150, 790, 161, 81))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(1150, 580, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(1140, 870, 181, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1150, 690, 171, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        myApp.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(myApp)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1319, 22))
        self.menuBar.setObjectName("menuBar")
        myApp.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(myApp)
        self.statusBar.setObjectName("statusBar")
        myApp.setStatusBar(self.statusBar)

        self.retranslateUi(myApp)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_12.clicked.connect(self.textEdit.clear)
        self.pushButton_2.clicked.connect(self.tableWidget.clearContents)
        self.pushButton_14.clicked.connect(self.pushButton_14.click)
        self.lineEdit_2.selectionChanged.connect(self.lineEdit_2.update)
        self.pushButton_16.clicked.connect(self.textEdit_2.clear)
        QtCore.QMetaObject.connectSlotsByName(myApp)

    def retranslateUi(self, myApp):
        _translate = QtCore.QCoreApplication.translate
        myApp.setWindowTitle(_translate("myApp", "myApp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("myApp", "Data Visualization"))
        self.label_2.setText(_translate("myApp", "SN List File Path"))
        self.pushButton_6.setText(_translate("myApp", "Loading"))
        self.pushButton_7.setText(_translate("myApp", "Delete"))
        self.label_3.setText(_translate("myApp", "Log Key :"))
        self.pushButton_8.setText(_translate("myApp", "Start Download"))
        self.label_4.setText(_translate("myApp", "PDCA Info:"))
        self.lineEdit_4.setText(_translate("myApp", "17.239.64.36"))
        self.label_5.setText(_translate("myApp", "IP"))
        self.label_6.setText(_translate("myApp", "User name"))
        self.label_7.setText(_translate("myApp", "Pass Word"))
        self.label_8.setText(_translate("myApp", "Download Yield and Retry Report From Time to Time"))
        self.label_9.setText(_translate("myApp", "Start Time"))
        self.label_10.setText(_translate("myApp", "End Time"))
        self.pushButton_10.setText(_translate("myApp", "Start"))
        self.pushButton_12.setText(_translate("myApp", "Clear up"))
        self.pushButton_15.setText(_translate("myApp", "State Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("myApp", "Data Download"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("myApp", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("myApp", "STATION NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("myApp", "PASS "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("myApp", "FAIL "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("myApp", "TOTAL"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("myApp", "YIELD RATE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("myApp", "RETRY RATE"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("myApp", "TIME FROM"))
        self.pushButton.setText(_translate("myApp", "Load"))
        self.pushButton_2.setText(_translate("myApp", "Delete"))
        self.pushButton_3.setText(_translate("myApp", "Export"))
        self.pushButton_4.setText(_translate("myApp", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("myApp", "Data Table"))
        self.groupBox.setTitle(_translate("myApp", "Function Column"))
        self.pushButton_13.setText(_translate("myApp", "PushButton"))
        self.pushButton_16.setText(_translate("myApp", "Clear Up"))
        self.pushButton_14.setText(_translate("myApp", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("myApp", "Little Tools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("myApp", "Waiting for update"))
        self.pushButton_5.setText(_translate("myApp", "Loading"))
        self.label.setText(_translate("myApp", "Key Point"))
        self.pushButton_9.setText(_translate("myApp", "SHOW"))
        self.label_11.setText(_translate("myApp", "Data Visualization"))
        self.pushButton_11.setText(_translate("myApp", "Pic Store"))

