#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# @Time     : 2018/2/8下午1:13
# @Author   : Saseny Zhou
# @Site     : 
# @File     : ui_main.py
# @Software : PyCharm


from PyQt5 import QtCore, QtGui, QtWidgets
from functions.path import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 505)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(images + "/Dashboard.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(31, 32))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_2.setMinimumSize(QtCore.QSize(220, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout.addWidget(self.listWidget_2)
        self.listWidget_3 = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_3.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_3.setObjectName("listWidget_3")
        self.horizontalLayout.addWidget(self.listWidget_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMouseTracking(False)
        self.toolBar.setTabletTracking(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(images + "/Home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon1)
        self.actionHome.setObjectName("actionHome")
        self.actionOpen_Result = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(images + "/Folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Result.setIcon(icon2)
        self.actionOpen_Result.setObjectName("actionOpen_Result")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(images + "/Burn.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon3)
        self.actionStart.setObjectName("actionStart")
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen_Result)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)

        self.actionHome.triggered.connect(self.home)
        self.actionStart.triggered.connect(self.running)
        self.actionOpen_Result.triggered.connect(self.open)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AuditTools"))
        self.label.setText(_translate("MainWindow", "Project"))
        self.label_2.setText(_translate("MainWindow", "Station"))
        self.label_3.setText(_translate("MainWindow", "Choose"))
        self.listWidget.setToolTip(_translate("MainWindow", "Double Click Choose"))
        self.listWidget_2.setToolTip(_translate("MainWindow", "Double Click Choose"))
        self.listWidget_3.setToolTip(_translate("MainWindow", "- Double Click Set-up \n"
                                                              "  when you double click then will show set-up window"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionHome.setToolTip(_translate("MainWindow", "Home Setup \n"
                                                            "<ctrl + H>"))
        self.actionHome.setShortcut(_translate("MainWindow", "Meta+H"))
        self.actionOpen_Result.setText(_translate("MainWindow", "Open Result"))
        self.actionOpen_Result.setToolTip(_translate("MainWindow", "Open Result File Folder \n"
                                                                   "<ctrl + O>"))
        self.actionOpen_Result.setShortcut(_translate("MainWindow", "Meta+O"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "Start To Run and Open State Window \n"
                                                             "<ctrl + R>"))
        self.actionStart.setShortcut(_translate("MainWindow", "Meta+R"))
